# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: AIR-ALL

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [AIROHA-WIFI-NO]
        SOURCE: [bingoguo93/immortalwrt]
        BRANCH: [6.18]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_THEME: aurora
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.1.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}

      WRT_PACKAGE: |
        CONFIG_PACKAGE_luci-app-passwall=y
        CONFIG_PACKAGE_xray-core=y
        CONFIG_PACKAGE_chinadns-ng=y
        CONFIG_PACKAGE_dns2socks=y
        CONFIG_PACKAGE_ipt2socks=y
        CONFIG_PACKAGE_tcping=y

        CONFIG_PACKAGE_lucky=y
        CONFIG_PACKAGE_luci-app-lucky=y
        CONFIG_PACKAGE_luci-i18n-lucky-zh-cn=y

        CONFIG_PACKAGE_microsocks=y
        CONFIG_PACKAGE_luci-app-microsocks=y

        CONFIG_PACKAGE_luci-app-gecoosac=y

        CONFIG_PACKAGE_luci-app-mosdns=n
        CONFIG_PACKAGE_luci-i18n-mosdns-zh-cn=n
        CONFIG_PACKAGE_mosdns=n
        CONFIG_PACKAGE_v2dat=n

        CONFIG_PACKAGE_luci-app-store=n
        CONFIG_PACKAGE_luci-lib-taskd=n
        CONFIG_PACKAGE_luci-lib-xterm=n
        CONFIG_PACKAGE_taskd=n

        CONFIG_PACKAGE_luci-app-daed=n
        CONFIG_PACKAGE_daed=n
        CONFIG_PACKAGE_luci-app-openclash=n
        CONFIG_PACKAGE_luci-app-passwall2=n
        CONFIG_PACKAGE_luci-app-nikki=n
        CONFIG_PACKAGE_luci-app-momo=n
        CONFIG_PACKAGE_luci-app-homeproxy=n
        CONFIG_PACKAGE_homeproxy=n
        CONFIG_PACKAGE_sing-box=n
        CONFIG_PACKAGE_luci-app-samba4=n
        CONFIG_PACKAGE_luci-app-upnp=n
        CONFIG_PACKAGE_luci-app-wolplus=n
        CONFIG_PACKAGE_luci-app-mini-diskmanager=n
        CONFIG_PACKAGE_luci-app-partexp=n
        CONFIG_PACKAGE_luci-app-qbittorrent=n
        CONFIG_PACKAGE_luci-app-openlist2=n

      WRT_TEST: ${{inputs.TEST}}
